name: Run Cookie Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:
jobs:
  Build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - name: Build Backend
        working-directory: ./backend
        run: go build -v ./...
      - name: Build Frontend
        working-directory: ./frontend
        run: go build -v ./...
      - name: Test
        working-directory: ./frontend
        run: go test -v ./...
