name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github'
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 6 * *'
  workflow_dispatch:
jobs:
  example:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Say My Name
        run: echo Say My Name
