name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches: 
      - main
  schedule:
    - cron: '15 6 6 * *'
  workflow_dispatch:
    inputs:
      environment:
        required: true
        default: 'Test'
        description: Select environment
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Event
        run: echo Event is ${{ github.event_name }} 
      - name: Repo
        run: echo Repo is ${{ github.ref }} 
      - name: List
        run: |
          ls -la .
          tree
  RunOnTest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo huhu
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    
