name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  workflow_dispatch:
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: List
        run: |
          ls -la .
          tree
      - name: Say It
        uses: ./actions
        with:
          who-to-greet: 'Mr. White'
