name: Reusable
run-name: ubuntu-latest
on: 
  workflow_call:
    inputs: 
      whotogreet:
        type: string
        description: "naf"
        default: 'World'
    outputs:
      current-time:
        description: Current Time
        value: ${{ jobs.reusable-job.outputs.current-time }}
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
        - name: SayIt
          run: echo 'Hello ${{ inputs.whotogreet }}'
        - name: WhatsTheTime
          id: time
          run: echo "Time is $(date)" >> $GITHUB_OUTPUT
